---
- name: Gather the package facts - Branch Connector Lab
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: pkg

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: Get janus version
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['janus'][0].version }} version of janus is installed!"
      when: "'janus' in ansible_facts.packages"